// tslint:disable
/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GarbagebinsFields,
    GarbagebinsFieldsFromJSON,
    GarbagebinsFieldsFromJSONTyped,
    GarbagebinsFieldsToJSON,
} from './';

/**
 * 
 * @export
 * @interface Filter
 */
export interface Filter {
    /**
     * 
     * @type {object}
     * @memberof Filter
     */
    where?: object;
    /**
     * 
     * @type {GarbagebinsFields}
     * @memberof Filter
     */
    fields?: GarbagebinsFields;
    /**
     * 
     * @type {number}
     * @memberof Filter
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof Filter
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof Filter
     */
    skip?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof Filter
     */
    order?: Array<string>;
}

export function FilterFromJSON(json: any): Filter {
    return FilterFromJSONTyped(json, false);
}

export function FilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): Filter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'where': !exists(json, 'where') ? undefined : json['where'],
        'fields': !exists(json, 'fields') ? undefined : GarbagebinsFieldsFromJSON(json['fields']),
        'offset': !exists(json, 'offset') ? undefined : json['offset'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'skip': !exists(json, 'skip') ? undefined : json['skip'],
        'order': !exists(json, 'order') ? undefined : json['order'],
    };
}

export function FilterToJSON(value?: Filter): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'where': value.where,
        'fields': GarbagebinsFieldsToJSON(value.fields),
        'offset': value.offset,
        'limit': value.limit,
        'skip': value.skip,
        'order': value.order,
    };
}


