// tslint:disable
/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GarbageBinExcludingId
 */
export interface GarbageBinExcludingId {
    /**
     * 
     * @type {number}
     * @memberof GarbageBinExcludingId
     */
    latitude: number;
    /**
     * 
     * @type {number}
     * @memberof GarbageBinExcludingId
     */
    longitude: number;
}

export function GarbageBinExcludingIdFromJSON(json: any): GarbageBinExcludingId {
    return GarbageBinExcludingIdFromJSONTyped(json, false);
}

export function GarbageBinExcludingIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): GarbageBinExcludingId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'latitude': json['latitude'],
        'longitude': json['longitude'],
    };
}

export function GarbageBinExcludingIdToJSON(value?: GarbageBinExcludingId): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'latitude': value.latitude,
        'longitude': value.longitude,
    };
}


