// tslint:disable
/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GarbageBinExcludingId
 */
export interface GarbageBinExcludingId {
    /**
     * 
     * @type {number}
     * @memberof GarbageBinExcludingId
     */
    latitude: number;
    /**
     * 
     * @type {number}
     * @memberof GarbageBinExcludingId
     */
    longitude: number;
    /**
     * 
     * @type {string}
     * @memberof GarbageBinExcludingId
     */
    userId?: string;
    /**
     * 
     * @type {number}
     * @memberof GarbageBinExcludingId
     */
    approvalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof GarbageBinExcludingId
     */
    rejectionCount?: number;
}

export function GarbageBinExcludingIdFromJSON(json: any): GarbageBinExcludingId {
    return GarbageBinExcludingIdFromJSONTyped(json, false);
}

export function GarbageBinExcludingIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): GarbageBinExcludingId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'latitude': json['latitude'],
        'longitude': json['longitude'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'approvalCount': !exists(json, 'approvalCount') ? undefined : json['approvalCount'],
        'rejectionCount': !exists(json, 'rejectionCount') ? undefined : json['rejectionCount'],
    };
}

export function GarbageBinExcludingIdToJSON(value?: GarbageBinExcludingId): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'latitude': value.latitude,
        'longitude': value.longitude,
        'userId': value.userId,
        'approvalCount': value.approvalCount,
        'rejectionCount': value.rejectionCount,
    };
}


