// tslint:disable
/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GarbageBinPartial
 */
export interface GarbageBinPartial {
    /**
     * 
     * @type {number}
     * @memberof GarbageBinPartial
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof GarbageBinPartial
     */
    longitude?: number;
    /**
     * 
     * @type {string}
     * @memberof GarbageBinPartial
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GarbageBinPartial
     */
    userId?: string;
    /**
     * 
     * @type {number}
     * @memberof GarbageBinPartial
     */
    approvalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof GarbageBinPartial
     */
    rejectionCount?: number;
}

export function GarbageBinPartialFromJSON(json: any): GarbageBinPartial {
    return GarbageBinPartialFromJSONTyped(json, false);
}

export function GarbageBinPartialFromJSONTyped(json: any, ignoreDiscriminator: boolean): GarbageBinPartial {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'latitude': !exists(json, 'latitude') ? undefined : json['latitude'],
        'longitude': !exists(json, 'longitude') ? undefined : json['longitude'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'approvalCount': !exists(json, 'approvalCount') ? undefined : json['approvalCount'],
        'rejectionCount': !exists(json, 'rejectionCount') ? undefined : json['rejectionCount'],
    };
}

export function GarbageBinPartialToJSON(value?: GarbageBinPartial): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'latitude': value.latitude,
        'longitude': value.longitude,
        'id': value.id,
        'userId': value.userId,
        'approvalCount': value.approvalCount,
        'rejectionCount': value.rejectionCount,
    };
}


