// tslint:disable
/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse2001
 */
export interface InlineResponse2001 {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001
     */
    greeting?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001
     */
    date?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001
     */
    url?: string;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof InlineResponse2001
     */
    headers?: { [key: string]: object; };
}

export function InlineResponse2001FromJSON(json: any): InlineResponse2001 {
    return InlineResponse2001FromJSONTyped(json, false);
}

export function InlineResponse2001FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2001 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'greeting': !exists(json, 'greeting') ? undefined : json['greeting'],
        'date': !exists(json, 'date') ? undefined : json['date'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'headers': !exists(json, 'headers') ? undefined : json['headers'],
    };
}

export function InlineResponse2001ToJSON(value?: InlineResponse2001): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'greeting': value.greeting,
        'date': value.date,
        'url': value.url,
        'headers': value.headers,
    };
}


