// tslint:disable
/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserExcludingId
 */
export interface UserExcludingId {
    /**
     * 
     * @type {string}
     * @memberof UserExcludingId
     */
    avatarUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof UserExcludingId
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserExcludingId
     */
    email: string;
}

export function UserExcludingIdFromJSON(json: any): UserExcludingId {
    return UserExcludingIdFromJSONTyped(json, false);
}

export function UserExcludingIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserExcludingId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'avatarUrl': !exists(json, 'avatarUrl') ? undefined : json['avatarUrl'],
        'username': json['username'],
        'email': json['email'],
    };
}

export function UserExcludingIdToJSON(value?: UserExcludingId): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'avatarUrl': value.avatarUrl,
        'username': value.username,
        'email': value.email,
    };
}


