// tslint:disable
/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    GarbageBin,
    GarbageBinFromJSON,
    GarbageBinToJSON,
} from '../models';

export interface AwardGarbageBinControllerGetGarbageBinRequest {
    id: string;
}

/**
 * no description
 */
export class AwardGarbageBinControllerApi extends runtime.BaseAPI {

    /**
     */
    async awardGarbageBinControllerGetGarbageBinRaw(requestParameters: AwardGarbageBinControllerGetGarbageBinRequest): Promise<runtime.ApiResponse<Array<GarbageBin>>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling awardGarbageBinControllerGetGarbageBin.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/awards/{id}/garbage-bin`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GarbageBinFromJSON));
    }

   /**
    */
    async awardGarbageBinControllerGetGarbageBin(requestParameters: AwardGarbageBinControllerGetGarbageBinRequest): Promise<Array<GarbageBin>> {
        const response = await this.awardGarbageBinControllerGetGarbageBinRaw(requestParameters);
        return await response.value();
    }

}
